# Tamaño máximo de datos a través del método POST
post_max_size = 41M
# Tamaño máximo de archivos permitidos para cargar al servidor
upload_max_filesize = 13M
# Número máximo de archivos que se pueden cargar mediante una sola solicitud
max_file_uploads = 53
# Cantidad máxima de memoria que un script puede asignar
memory_limit= 512M
# Tiempo máximo de ejecución de cada script, en segundos
max_execution_time = 300
