[uwsgi]
plugins=php
processes=2
master=true
cheaper=1
uid=server
gid=server
log-x-forwarded-for=true
max-requests=521
post-buffering=4096
buffer-size=6144
harakiri=521
harakiri-verbose=true
socket=192.168.11.10:1597
project_dir = /var/www/html/kavac/public/
chdir=%(project_dir)
; jail our php environment to project_dir
php-docroot = %(project_dir)
php-allowed-docroot = %(project_dir)
; ... and to the .php and .inc extensions
php-allowed-ext = .php
php-allowed-ext = .inc
; and search for index.php and index.inc if required
php-index = index.php
php-index = index.inc
